### PR TITLE
write jpeg to stdout

### PR DESCRIPTION
**Pull request by cmeissl**
A draft of a working example on how to use shm and image to write the
output content to stdout

### CODE REVIEW

**Comment by Shinyzenith** [comment]
Hi! `Error: Unsupported buffer format: Xbgr8888` I get the following error on attempting to run your branch.

**Comment by cmeissl** [comment]
I will fix it later today.

**Comment by cmeissl** [comment]
> Hi! `Error: Unsupported buffer format: Xbgr8888` I get the following error on attempting to run your branch.

My nested sway instance only reports Argb8888, but I changed the code to check the format.
I also added Xrgb888, but have not tested it. Can you check again?

**Comment by HeavyRain266** [comment]
@cmeissl On nested sway instance gives me `Error: no suitable format frame`.

**Comment by cmeissl** [comment]
> @cmeissl On nested sway instance gives me `Error: no suitable frame format`.

That is interessting, so neither `Argb8888` nor `Xrgb8888` are reported from the compositor?
I have added a debug log output for the received formats. Can you run it with `RUST_LOG=debug cargo run > /tmp/image.jpeg` and post the reported formats please?

**Comment by HeavyRain266** [comment]
> > @cmeissl On nested sway instance gives me `Error: no suitable frame format`.
> 
> That is interessting, so neither `Argb8888` nor `Xrgb8888` are reported from the compositor?
> I have added a debug log output for the received formats. Can you run it with `RUST_LOG=debug cargo run > /tmp/image.jpeg` and post the reported formats please?

I think I'd just forgot to do `cargo run > /tmp/image.jpeg` and ran `cargo run` instead and now it works.

**Comment by Shinyzenith** [comment]
Sat

**Comment by Shinyzenith** [comment]
Sat

**Comment by cmeissl** [comment]
> Sat

Ah, ok, it uses `Xbgr8888`, I added the format, but did not check the endianness so the colors may be off.

**Comment by HeavyRain266** [comment]
I think it should show more descriptive error on unsupported compositors, something like "Compositor does not implement wlr-screencopy-v1" which is much better than error about missing globals.

**Comment by cmeissl** [comment]
> I think it should show more descriptive error on unsupported compositors, something like "Compositor does not implement wlr-screencopy-v1" which is much better than error about missing globals.

Yes, the error handling definitely needs to be enhanced. The PR only represents some starting point as written.
I am not sure I will have time to contribute to another project at this time, already too many things on my todo list.

**Comment by Shinyzenith** [comment]
Wow this works!! I will definitely make sure to learn from it and utilize it to the best of my abilities.

**Comment by Shinyzenith** [comment]
> So, this should only provide a starting point. Some ideas for enhancing it:
> 
>     * Support for more shm formats
> 
>     * Check if stdout is a terminal, could be done by using [atty](https://crates.io/crates/atty), and error out
> 
>     * Adding support for command line arguments, could use [clap](https://crates.io/crates/clap) like
>       
>       * selecting which output to use
>       * specifying a file path
>       * allow to take a screenshot from a geometry and using [capture_output_region](https://wayland.app/protocols/wlr-screencopy-unstable-v1#zwlr_screencopy_manager_v1:request:capture_output_region)
> 
>     * adding a timeout in case the buffer failed/finished event takes too long

Added capture_output_region support via slurp.

**Comment by Shinyzenith** [comment]
Will work on output detection. I don't think specifying file is really needed , as long as something goes to stdout we can just pipe it to a file, I'll let the users implement that XD

**Pull request merged**
